# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G

minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.16.5

# Fabric API
fabric_version=0.103.0+1.21.1

# Mod Properties
mod_version = 1.1.7
maven_group = net.pitan76
archives_base_name = PipePlus

libblockattributes_version=0.16.0-pre.2
libnetworkstack_version=0.13.0-pre.1
libmultipart_version=0.13.0-pre.3
simplepipes_version=0.13.1

rei_version=16.0.762

mcpitanlib_version=+1.21.1:3.1.5
mcpitanlib_checker_version=1.0.4